services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: insightlog-api
    volumes:
      - sqlite-data:/app

volumes:
  sqlite-data:

