// <auto-generated />
using System;
using InsightLog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsightLog.Infrastructure.Migrations
{
    [DbContext(typeof(InsightLogDbContext))]
    [Migration("20250511105449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("InsightLog.Domain.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoodTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("InsightLog.Domain.Entities.JournalEntry", b =>
                {
                    b.OwnsOne("InsightLog.Domain.ValueObjects.AISummary", "Summary", b1 =>
                        {
                            b1.Property<Guid>("JournalEntryId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("GeneratedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("AISummaryGeneratedAt");

                            b1.Property<string>("SummaryText")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("AISummaryText");

                            b1.HasKey("JournalEntryId");

                            b1.ToTable("JournalEntries");

                            b1.WithOwner()
                                .HasForeignKey("JournalEntryId");
                        });

                    b.Navigation("Summary");
                });
#pragma warning restore 612, 618
        }
    }
}
